### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by ulrichb** [nsigustavo/ludibrio#1]
When I use Ludibrio in Python 2.7 with the "-3" parameter, I get the following 2 warnings:

\ludibrio_testdouble.py:2: DeprecationWarning: Overriding **eq** blocks inheritance of **hash** in 3.x
  class _TestDouble(object):
\ludibrio\specialarguments.py:5: DeprecationWarning: Overriding __eq__ blocks inheritance of **hash** in 3.x
  class matcher(object):

**Comment by nsigustavo** [comment]
I can not remove it.
