### ISSUE TITLE
import issue for specialarguments matcher 

### ISSUE THREAD

**Issue by generalov** [nsigustavo/ludibrio#4]
Hello. 
I doesn't like a "star" imports `from ludibrio.matcher import *` and I want use the `ludibrio.matcher.any` prefixed by its module path:

```
import ludibrio

with ludibrio.Mock() as connection:
    connection.request('/root.ws', ludibrio.matcher.any()) >> 'response'
```

But I got exception:

   AttributeError: type object 'matcher' has no attribute 'any'

I try to import matcher module with `from ludibrio import matcher` and I got matcher decorator too.

It's seems 'ludibrio.matcher' module (collection of matchers) conflicts by name with 'ludibrio.specialarguments.matcher' decorator. Is this expected?

**Comment by nsigustavo** [comment]
```
import ludibrio
with ludibrio.Mock() as connection:
    connection.request('/root.ws', ludibrio.any()) >> 'response'
print connection.request('/root.ws', 'dummy')  
```

**Comment by generalov** [comment]
Thanks, this works!

I missed this in the documentation and look specification in the
http://github.com/nsigustavo/ludibrio/blob/ludibrio3.0/ludibrio/specification/unit/specialarguments/any_of.dt .

**Comment by nsigustavo** [comment]
ok
